name: 'r2_pipeline'
version: '1.0.0'
profile: 'r2'
config-version: 2

model-paths: ["models"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  r2_pipeline:
    raw:
      +schema: raw
      +materialized: view
      +tags: ["raw"]
    silver:
      +schema: silver
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: ignore
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]

snapshots:
  r2_pipeline:
    +target_schema: snapshots
    +tags: ["snapshots"]
